### ISSUE TITLE
Easily replaceable `getValidationMessage` function

### ISSUE THREAD

**Issue by kopecmi8** [eManPrague/frui.ts#34]
If you want to use own validator instead of prepared one could be usefull to easily replace `getValidationMessage` [helper](https://github.com/eManPrague/frui.ts/blob/develop/packages/validation/src/helpers.ts#L35). 

Almost every [control ](https://github.com/eManPrague/frui.ts/blob/develop/packages/bootstrap/src/controls/validationControlBase.tsx#L39) use this helper function to detect if the error is visible. 

For example if you need show error "onBlur" of input, the only way how to do its own implementation of each input or monkey patch the ControlBase prototype and override whole `getValidationError` method.  With configurable helpers this could be much more comfortable.

**Comment by gius** [comment]
@kopecmi8 Is this resolved with the new validation package?
