### ISSUE TITLE
Specify Screen name with getter and setter

### ISSUE THREAD

**Issue by kopecmi8** [eManPrague/frui.ts#36]
I´am using getter to specify ScreenBase name because of localization.  After upgrade to Typescript 4.x  there is an error beacuse originally its  `name` atributte specified as public member not a getter..

I suggest to change current
```

@observable name: string;
```

To something like this
```
@observable protected nameValue: string;

@computed
get name() {
 return this.nameValue;
}

set name(name: string) {
  this.nameValue = name;
}
```

Which should be fully compatible and more etensionible

**Comment by gius** [comment]
Implemented fc50f7cbb119586e335205b3e8f8554c821d32ef
