### ISSUE TITLE
ConductorOneChildActive - easily prevent automatic activation of next children

### ISSUE THREAD

**Issue by kopecmi8** [eManPrague/frui.ts#37]
There are two patterns ConductorOneChildActive and ConductorSingleChild.  But no one of them solves situation if you have "finite list of potentional children" but you dont want to activate next child in order after closing one.

I thing if you have finitite list of child its better to use ConductorOneChildActive than ConductorSingleChild because of `children` array existency. But [the mechanism determination of nextChildToActivate](https://github.com/eManPrague/frui.ts/blob/183c00cc76b211b99c1e51db6250e1d9887c61e8/packages/screens/src/structure/conductorOneChildActive.ts#L70) is little bit weird.  The situation is not improved by the fact that the  `determineNextChildToActivate` method is private and cannot be easilly overloaded.

I thing this mechanism should be easilly turn off by specifiing some flag or at least should be possible to overload by declaring `determineNextChildToActivate` as protected.

**Comment by gius** [comment]
Irrelevant in v1 - the behavior depends on the actually used router.
