### ISSUE TITLE
View component with useLifecycle doesn't run activate when VM being changed

### ISSUE THREAD

**Issue by kopecmi8** [eManPrague/frui.ts#49]
Due to refactor inside [View component](https://github.com/eManPrague/frui.ts/blob/v0.15.0/packages/views/src/view.tsx) between versions 0.15.0 and 0.16.0 error occur when you try to update.

Consider for following code:
```
function renderViewModel(viewModel: any) {
  ReactDOM.render(<View vm={viewModel} useLifecycle />, document.getElementById("root"));
}
```

When you changes viewModel via prop at 0.15.0 `activate` callback run [always](https://github.com/eManPrague/frui.ts/blob/v0.15.0/packages/views/src/view.tsx#L24).  Now in 0.16.0 (and higher) activation callback run only when [componentDidMount ](https://github.com/eManPrague/frui.ts/blob/v0.16.0/packages/views/src/view.tsx#L34) and doesn't run when VM being  changed.

**Comment by gius** [comment]
Merged
