### ISSUE TITLE
Explore alternatives to Lerna

### ISSUE THREAD

**Issue by gius** [eManPrague/frui.ts#72]
https://javascript.plainenglish.io/5-best-lerna-alternatives-42ffe75d403e

**Comment by kareldurdis** [comment]
I'd add lerna-lite to the list https://github.com/ghiscoding/lerna-lite

Although it looks like Lerna will live again as ppl from Nx are taking over. https://github.com/lerna/lerna/issues/3121

**Comment by juristr** [comment]
Yep, we just released v5 a couple of weeks ago and 5.1 last week drastically improving Lerna's speed: https://dev.to/nx/lerna-used-to-walk-now-it-can-fly-3661

**Comment by gius** [comment]
The latest Lerna powered by Nx seems ok ;-)
