### ISSUE TITLE
Navigation adapter cause error when user use back button and then want to navigate to same page.

### ISSUE THREAD

**Issue by kopecmi8** [eManPrague/frui.ts#9]
When user use back button and than want to go to same screen where has been, this condition https://github.com/eManPrague/frui.ts/blob/08450c1a3c3183a5b49459c0fb1ee696198f7fe0/packages/screens/src/navigation/urlNavigationAdapter.ts#L33 prevents to propage URL to the navigation bar.  Problem is at `onUrlChange` method (https://github.com/eManPrague/frui.ts/blob/develop/packages/screens/src/navigation/urlNavigationAdapter.ts#L41)  because it doesnt change the `lastUrl`....

**Comment by kopecmi8** [comment]
I try to fix it at https://github.com/eManPrague/frui.ts/pull/10

**Comment by gius** [comment]
Thank you for the report!
Please check the latest version v0.15.0-beta.5, it should be fixed there.
